name: Build Jar

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Move Gradle files to easybot_bukkit
      run: |
        mv gradlew easybot_bukkit/
        mkdir -p easybot_bukkit/gradle/wrapper
        cp -r gradle/wrapper/* easybot_bukkit/gradle/wrapper/
      
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      working-directory: easybot_bukkit

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: easybot_bukkit

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: easybot-bukkit-jar
        path: build/libs/*.jar